sudo: false

language: scala

jdk:
  - oraclejdk8

scala:
  - 2.12.6

script: sbt compile test publishMicrosite

before_install:
 - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.2.8 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1