name: retry4s
baseurl: /retry4s
description: Purely functional retry combinators for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.0-SNAPSHOT
org: com.mdipaola
markdown: kramdown
